[package]
name = "rltk"
version = "0.1.0"
authors = ["ddmills <mills.dalton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
